name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, ubuntu-latest, windows-latest ]
        node: [ 16 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Compile TypeScript to JavaScript
        run: npm run compile
      - name: Lint TypeScript
        run: npm run lint
      - name: Run test cases
        run: npm test
